### PR TITLE
Added python code for all patterns 

### PR DESCRIPTION
**Pull request by PranilMeherkar**
Added all patterns in python code in their respective directories and also created directories for the patterns that were not present.

### CODE REVIEW

**Comment by kmryashasvi** [comment]
hello
I am delighted to have your massive and valuable contribution to this repo
Question numbers 10,11,12,14and 15 have already python codes in them
this is the cause of conflict
please make sure your codes are not a repeated version of the codes
please change file names to Q10.2.py  ,Q11.2.py  ,Q12.2.py  ,Q14.2.py  ,Q15.2.py repsectively

**Comment by PranilMeherkar** [comment]
Change the required file names, no conflicts left

**Comment by kmryashasvi** [comment]
Please contribute in other languages too,
Sticking to only one code in this era is not enough.

**Comment by PranilMeherkar** [comment]
Yeah sure, actually im new to github and python is the most recent language that i'd learnt... Like in dec...so wrote the codes in python

**Pull request merged**
