### PR TITLE
Adding Q21.c

### PR DESCRIPTION
**Pull request by Shubham-Vishwakarma**

### CODE REVIEW

**Comment by Shubham-Vishwakarma** [comment]
why are the checks failing?

**Comment by Shubham-Vishwakarma** [comment]
image

**Comment by kmryashasvi** [comment]
That doesn't matter
Don't worry about that
It is only because you have not use schematic commit messages

**Comment by kmryashasvi** [comment]
Semantic

**Comment by kmryashasvi** [comment]
But please consider it next time

**Comment by Shubham-Vishwakarma** [comment]
@kmryashasvi 
If there such a constraint, it would be better if you mention this in Readme file
For beginner like me who are unaware of this fact, might raise this issue again and again.

**Pull request merged**
