### PR TITLE
Create Q39.java

### PR DESCRIPTION
**Pull request by ccolon11**

### CODE REVIEW

**Review by yashlikescode — CHANGES_REQUESTED** [review]
Please have a look, the program is misbehaving:
image
Run and test it in your local program and then try again

**Comment by ccolon11** [comment]
I have tried the fix several times, and the program works fine, with JDK 17, in intelliJ IDE. Do you see all the imports before running the program?
Capture

**Comment by yashlikescode** [comment]
when we are giving input a character, then why we are receiving a text that says numbers are not allowed,
it should directly print the pattern

**Comment by ccolon11** [comment]
because it is an example, where the logic of the program consists of entering a letter of the alphabet instead of a number, and from there, print the following letters of the ABC. I think it is a different way of doing it, and it serves as a learning tool for all those who visit the pattern repository. 

The user must necessarily enter a letter in the console from the beginning and not a number, and the pattern will be generated immediately.

**Comment by yashlikescode** [comment]
I am sad to say, but on this repository, we only publish the codes which are when entered a number, prints a pattern relative to that size, hope you understand

**Pull request closed without merging**
